### ISSUE TITLE
Module update

### ISSUE THREAD

**Issue by RobAatISC** [leeford/Backup-TeamsConfig#3]
The required Skype module appears to have been [superseded](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide) by the 'MicrosoftTeams' module.  I was able to get the script working by modifying the module check to 'MicrosoftTeams', and replacing 'new-csonlinessession' with 'connect-teams'.  All of the commands seemed to work except 'Get-CsTeamsWorkLoadPolicy', which was unrecognized.  Not sure if there are any other modifications that should be made to bring it in line with the newer module.

**Comment by leeford** [comment]
@RobAatISC I did change it already but forgot to create a new release for it! 

I've just added code to check for an existing session (to save being asked to sign-in each time) and created a new release. As for `Get-CSTeamsWorkLoadPolicy` - it is listed in the Teams module cmdlets but doesn't seem to be implemented within the back-end yet, so I suspect this will work once they do.
