### ISSUE TITLE
Missing Voice items

### ISSUE THREAD

**Issue by MichaelLaMontagne** [leeford/Backup-TeamsConfig#5]
CsCallingLineIdentity
CsOnlineLisCivicAddress
CsOnlineLisLocation
CsOnlineLisPort
CsOnlineLisSubnet
CsOnlineLisWirelessAccessPoint
csTeamsUnassignedNumberTreatment

**Comment by MichaelLaMontagne** [comment]
Adding the below works, but doesn't work with the "Number of Items".       


   Get-Command "Get-CSonline*lis*" | ForEach-Object {

                $policy = $_.Name -replace "Get-CS", ""
                Backup-Configuration -Type $policy

            }
            
            Get-Command "Get-CScalling*" | ForEach-Object {

                $policy = $_.Name -replace "Get-CS", ""
                Backup-Configuration -Type $policy

            }

            Get-Command "Get-CS*UnassignedNumber*" | ForEach-Object {

                $policy = $_.Name -replace "Get-CS", ""
                Backup-Configuration -Type $policy

            }

**Comment by leeford** [comment]
Hey @MichaelLaMontagne - totally missed this. Let me take a look :+1:

**Comment by leeford** [comment]
I've updated the script to include these items and count all items correctly. Thanks @MichaelLaMontagne
